[package]
edition = "2021"
name = "twitch-chat"
version = "0.1.0"

[dependencies]
crossbeam = "0.8.1"
crossterm = "0.23.0"
nom = "7.1.0"
rand = "0.8.0"
tungstenite = "0.17.1"
unicode-width = "0.1.9"
url = "2.2.2"

[dependencies.chrono]
features = ["unstable-locales"]
version = "0.4"
