[package]
edition = "2021"
name = "twitch-chat"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"]}
rand = "0.8.0"
crossbeam = "*"
crossterm = "*"
nom = "*"
tungstenite = "*"
unicode-width = "*"
url = "*"
